function shadow_std = shadowing_field(ue_track, cells, d_corr_m, seed)
%SHADOWING_FIELD  Spatially-correlated standard-normal shadowing field
%                 sampled at UE position for each cell.
%
% Implements the shadow fading correlation structure of
%   3GPP TR 38.901 v17.1.0 Table 7.5-6 (decorrelation distance per scenario)
% via a 2-D Gaussian Random Field per cell, generated by convolving white
% Gaussian noise on a regular grid with an exponential autocorrelation
% kernel, then sampling at the UE positions by bilinear interpolation.
%
% The returned field has approximately unit variance. Callers should
% multiply by the appropriate sigma (sigma_LoS or sigma_NLoS) to convert
% to dB-domain shadowing samples.
%
% Args:
%   ue_track : struct from `mobility.waypoint_track` (.t_s, .x_m, .y_m)
%   cells    : struct array from `utils.hex_layout`
%   d_corr_m : shadowing decorrelation distance (m)
%   seed     : RNG seed (scalar)
%
% Returns:
%   shadow_std : T × K, approximately N(0, 1), correlated over distance ~d_corr_m

arguments
    ue_track (1,1) struct
    cells    (:,1) struct
    d_corr_m (1,1) double {mustBePositive}  = 37
    seed     (1,1) double                   = 0
end

T = numel(ue_track.t_s);
K = numel(cells);

% --- grid spec ---
% resolution: small enough to resolve d_corr, but not so small that grid
% becomes huge. Empirically d_corr/4 works.
res    = d_corr_m / 4;
margin = 3 * d_corr_m;

cell_x = arrayfun(@(c_) c_.x_m, cells);
cell_y = arrayfun(@(c_) c_.y_m, cells);
xmin = min([ue_track.x_m; cell_x]) - margin;
xmax = max([ue_track.x_m; cell_x]) + margin;
ymin = min([ue_track.y_m; cell_y]) - margin;
ymax = max([ue_track.y_m; cell_y]) + margin;

x_grid = (xmin:res:xmax).';
y_grid = (ymin:res:ymax).';
nx = numel(x_grid); ny = numel(y_grid);

% --- exponential autocorrelation kernel ---
% truncate at 4*d_corr (kernel value ≈ exp(-4) ≈ 0.018)
k_half = ceil(4 * d_corr_m / res);
[KX, KY] = meshgrid(-k_half:k_half, -k_half:k_half);
d_kernel = sqrt(KX.^2 + KY.^2) * res;
kernel = exp(-d_kernel / d_corr_m);
% L2-normalize so that convolving with white unit-variance noise yields
% unit-variance output (Parseval / discrete-time convolution result).
kernel = kernel ./ sqrt(sum(kernel(:).^2));

% --- per-cell field generation + interpolation ---
shadow_std = zeros(T, K);
rng(seed, 'twister');
for k = 1:K
    noise = randn(ny, nx);
    field = conv2(noise, kernel, 'same');
    % numerical correction to unit variance (compensate for boundary effects)
    field = field ./ std(field(:), 0);
    % interp2 expects matrices oriented as Y rows × X cols; X and Y inputs
    % are vectors interpreted by meshgrid convention.
    shadow_std(:, k) = interp2(x_grid, y_grid, field, ...
                               ue_track.x_m, ue_track.y_m, 'linear', 0);
end
end
