function spec = baseline(overrides)
%BASELINE  Baseline scenario phase spec (UMa 3.5 GHz, 12 UEs, default HO).
%
% Returns a phase spec consumable by `utils.run_phase`. All fields can be
% overridden via the `overrides` struct (typically populated from the
% timeline JSON `params` block).
%
% Per ADR-14 every scenario is 5G NR SA, intra-RAT, inter-gNB Xn HO.

arguments
    overrides (1,1) struct = struct()
end

c = utils.constants();

spec = struct();
spec.scenario_name = "baseline";
spec.is_drift      = false;
spec.is_anomaly    = false;
spec.drift_id      = "";
spec.anomaly_id    = "";

% --- defaults ---
spec.n_ue        = 12;
spec.area_m      = 1500;
spec.speed_mps   = 10;
spec.duration_s  = 60;
spec.master_seed = 1;
spec.phase_id    = 1;
% List of anomaly specs to apply to this phase's measurements before the
% HO event loop runs. Each entry is a struct with at minimum:
%   .type            ("rlf_burst" | "meas_glitch" | "slow_degrade" | "interference_spike")
%   .t_start_s, .t_end_s   phase-local window (seconds)
%   .affected_ue_ids       vector of UE ids (empty = all UEs)
%   .affected_cell_ids     vector of cell ids (empty = all cells; used by interference_spike)
%   .delta_db / .stuck_value_dbm / .rate_db_per_s   (type-specific)
% The timeline builder populates this field by routing top-level
% `ground_truth_anomaly` entries to the matching phase by `phase_id`.
spec.anomalies   = {};

spec.layout_params = struct( ...
    'n_tiers', 2, ...
    'isd_m',   c.default_isd_m, ...
    'h_bs_m',  c.h_bs_m_uma);

spec.meas_params = struct( ...
    'fc_ghz',        c.default_fc_ghz, ...
    'h_bs_m',        c.h_bs_m_uma, ...
    'h_ut_m',        c.default_h_ut_m, ...
    'p_tx_dbm',      c.default_p_tx_dbm, ...
    'g_tx_dbi',      c.default_g_tx_dbi, ...
    'g_rx_dbi',      c.default_g_rx_dbi, ...
    'n_rb',          c.default_n_rb, ...
    'noise_bw_hz',   c.default_noise_bw_hz, ...
    'nf_db',         c.default_nf_db, ...
    'scenario',      "UMa", ...
    'sigma_los_db',  c.sigma_los_db_uma, ...
    'sigma_nlos_db', c.sigma_nlos_db_uma, ...
    'shadow_corr_m', c.shadow_corr_m_uma, ...
    'los_corr_m',    c.los_corr_m_uma);

spec.ho_params = struct( ...
    'dt_s',          c.sim_dt_s, ...
    'l3_alpha',      0.5, ...
    'ttt_s',         c.default_ttt_ms / 1000, ...
    'hyst_db',       c.default_hyst_db, ...
    'a3_offset_db',  c.default_a3_off_db, ...
    'ho_exec_s',     0.050, ...
    'rlf_qout_db',   c.rlf_sinr_threshold_db, ...
    'rlf_qin_db',    c.in_sync_sinr_db, ...
    'n310',          c.default_N310, ...
    'n311',          c.default_N311, ...
    't310_s',        c.default_T310_ms / 1000, ...
    'ping_pong_s',   c.ping_pong_window_s);

% --- apply overrides ---
spec = scenarios.apply_overrides(spec, overrides);
end
