function ev = empty_event()
%EMPTY_EVENT  Canonical empty HO/RLF event row.
%
% Schema mirrors `docs/schema.md` Section 2 "Event-level". Always return
% the same struct shape so vertical concatenation into a struct array
% works in `event_loop` (MATLAB requires identical field names + order).
ev = struct( ...
    'event_id',           0, ...
    'event_time_s',       NaN, ...
    'event_type',         "", ...   % HO_ATTEMPT | HO_SUCCESS | HO_FAIL | RLF | PING_PONG
    'ue_id',              0, ...
    'source_cell_id',     0, ...
    'target_cell_id',     0, ...
    'outcome',            "", ...   % success | fail | rlf | pp_fail
    'ttt_ms',             NaN, ...
    'hysteresis_db',      NaN, ...
    'a3_offset_db',       NaN, ...
    'trigger_quantity',   "RSRP", ...
    'rsrp_serv_pre_dbm',  NaN, ...
    'rsrp_tgt_pre_dbm',   NaN, ...
    'rsrp_serv_post_dbm', NaN, ...
    'sinr_serv_pre_db',   NaN, ...
    't_to_next_event_s',  NaN);
end
